backend/api/urls.py
from django.urls import path
from api.views import *


urlpatterns = [
    path('monitor', Monitoring.as_view(), name="monitors"),
    path('event', Event.as_view(), name="events"),
    path('pause-monitor', pause_monitor),
    path('start-monitor', start_monitor),
    path('notification', Notifications.as_view()),
    path('get-pages', get_pages),
    path('user-pages', UserPages.as_view()),
    path('monitor-page-stats/', monitor_page_stats),
    path('get-user-details', get_user_details)
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'), name='website'),
    path('api/', include('api.urls'), name='api'),
    path('payment/', include('payment.urls'), name='payment'),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/website/urls.py
from django.urls import path, re_path
from website.views import *
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


ANGULAR_PATHS = ["home", "pages", "profile", "plans"]

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('register/', Register.as_view() , name="register"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page = "/")),
    path('activation/', TemplateView.as_view(template_name = "offline/activation.html")),
    path('activate-account/<int:user>/<str:code>', activate_account),
    path('monitor/<int:id>', user_monitor),
    path('contact/', contact_form)
]

for url_path in ANGULAR_PATHS:
    urlpatterns.append(
        path(f"{url_path}", login_required(TemplateView.as_view(template_name="online/index.html")))
    )

app_name = 'website'

backend/templates/offline/activation.html
{% extends 'offline/root.html' %} {% load static %} {% block content %}
<div
  class="w-full md:w-2/4 xl:w-2/4 mx-auto flex flex-col gap-6 py-24 text-center rounded-xl px-12"
  action="
"
>
  <h1 class="text-headline text-2xl font-semibold font-lexend">Activate your account</h1>
  <p class="text-gray-700">
    An email has been sent to your email account, click on the link we sent you to activate your account and then you can login.
  </p>
</div>
{%endblock %}

backend/templates/offline/contact.html
<div class="max-w-1400 mx-auto pb-16 px-6 lg:px-0">
  <h2 class="font-lexend text-4xl mb-12 font-medium text-center">Contact us</h2>
  <form x-data="{isLoading: false}" onsubmit="contactForm(event, this)" class="gap-4 w-full lg:w-[600px] mx-auto main_form !px-0 !py-0 !border-none !bg-transparent !shadow-none">
    <input type="hidden" value="{{csrf_token}}" name="csrfmiddlewaretoken" />
    <input required type="text" name="name" placeholder="Your name" class="!rounded-md" />
    <input required type="email" name="email" id="" placeholder="Email" class="!rounded-md" />
    <textarea required name="text" cols="30" rows="10" placeholder="Tell us what you need" class="!rounded-md"></textarea>
    <button class="!text-md">
      <i x-show="isLoading" class="fa-solid fa-circle-notch fa-spin"></i>
      <span x-show="!isLoading">Submit</span>
    </button>
    <span @click="isLoading=true" class="hidden loading"></span>
    <span @click="isLoading=false" class="hidden loaded"></span>
  </form>
</div>

backend/templates/offline/faq.html
<div id="faq" class="max-w-1400 mx-auto grid gap-16 py-32 px-6 lg:px-16 2xl:px-0">
  <section>
    <h2 class="text-4xl font-lexend">Frequently asked questions</h2>
    <p class="text-gray-900 lg:w-1/2 mt-6">Got Questions? We've Got Answers! Your FAQ Guide</p>
  </section>
  <section
    class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-12"
    x-data="{questions: [
        {
            'Q': 'How do I create a monitor?',
            'R': 'After you login to your account at Statuscheks.net, click on the “Create” button. Add informations about your monitor and then click on create.'
        },
        {
            'Q': 'Does Statuschecks auto start the monitor whenever it is down?',
            'R': 'The monitor is still active when it’s down and checking if the service is back up.'
        },
        {
          'Q': 'Where are the monitoring locations ?',
          'R': 'All our servers are based in US north virginia region.'
        }
    ]}"
  >
    <template x-for="question in questions">
      <div>
        <h3 x-text="question.Q" class="text-lg font-lexend font-medium mb-4"></h3>
        <p x-text="question.R" class="text-gray-900"></p>
      </div>
    </template>
  </section>
</div>

backend/templates/offline/footer.html
{% load static %}
<footer class="text-center lg:py-16 flex flex-col lg:grid gap-8 max-w-[1000px] mx-auto px-6">
  <div class="flex flex-col lg:flex-row gap-8 lg:gap-0 justify-between items-center">
    <div class="flex flex-col items-cneter">
      <a id="logo" href="/">
        <img src="{% static 'logo.svg' %}" alt="" width="25" />
        <span> StatusChecks </span>
      </a>
    </div>
    <!-- <div class="flex gap-6">
      <a href="" class="bg-secondary grid place-content-center w-7 h-7 text-center rounded-full hover:bg-hover"
        ><i class="fa fa-facebook fa-sm text-gray-100"></i
      ></a>
      <a href="" class="bg-secondary grid place-content-center w-7 h-7 text-center rounded-full hover:bg-hover"
        ><i class="fa fa-twitter fa-sm text-gray-100"></i
      ></a>
      <a href="" class="bg-secondary grid place-content-center w-7 h-7 text-center rounded-full hover:bg-hover"
        ><i class="fa fa-linkedin fa-sm text-gray-100"></i
      ></a>
    </div> -->
  </div>
  <div class="flex flex-col-reverse lg:flex-row gap-6 lg:gap-0 justify-between items-center border-t lg:border-b-0 border-gray-300 py-6">
    <div class="text-sm text-gray-600 text-left mx-auto w-content whitespace-nowrap"><span>©</span> 2022 - All rights reserved</div>
    <div class="flex flex-col lg:flex-row justify-end w-full mx-auto gap-6 lg:gap-12 text-sm">
      <a href="#pricing" class="text-gray-600 hover:text-gray-900 duration-300">Pricing</a>
      <a href="#services" class="text-gray-600 hover:text-gray-900 duration-300">Services</a>
      <a href="#faq" class="text-gray-600 hover:text-gray-900 duration-300">FAQ</a>
      <a href="{% url 'website:login' %}" class="text-gray-600 hover:text-gray-900 duration-300">Login</a>
      <a href="{% url 'website:register' %}" class="text-gray-600 hover:text-gray-900 duration-300">Register</a>
      <!-- <a href="#faq" class="text-gray-600 hover:text-gray-900 duration-300">Blog</a> -->
    </div>
  </div>
</footer>

<!-- <span class="text-sm">©</span> 2022 - All rights reserved -->

backend/templates/offline/home.html
{% extends 'offline/root.html' %} {% load static %} {% block content %}
<div id="hero" style="min-height: calc(100vh - 104px)" class="px-6 lg:px-12 2xl:px-0 grid xl:place-content-center xl:-translate-y-8">
  <div class="2xl:w-8/12 mx-auto text-center grid gap-8 py-16 xl:py-0">
    <h1 class="text-5xl xl:text-7xl font-lexend font-medium leading-[60px] xl:leading-[85px]">Monitoring <span class="text-secondary">made simple</span> for businesses.</h1>
    <p class="mx-auto leading-8 text-lg">
      Are you tired of constantly worrying about website downtime or server issues? Our monitoring service has got you covered. With real-time monitoring, instant alerts, and detailed reports, you can
      stay on top of potential problems.
    </p>
    <div class="flex flex-col xl:flex-row gap-6 items-center mx-auto w-content">
      {% if not user.is_authenticated %}
      <a href="{% url 'website:register' %}" class="!bg-gray-900 main whitespace-nowrap">Register for free</a>
      {% else %}
      <a href="/home" class="!bg-gray-900 main whitespace-nowrap">Create a monitor</a>
      {% endif %}
      <!-- <a href="" class="bg-white shadow-md px-4 py-2 rounded-full flex gap-2 items-center hover:shadow-lg w-full justify-center whitespace-nowrap">
        <i class="fas fa-play text-secondary fa-xs"></i>
        Watch a video
      </a> -->
    </div>
  </div>
</div>
<div id="landing_2" class="py-36 px-6 lg:px-16 grid gap-16">
  <div class="text-gray-800 text-center grid gap-4 xl:w-10/12 mx-auto">
    <h2 class="text-5xl font-lexend font-semibold leading-relaxed">The all-in-one solution for keeping your services running smoothly.</h2>
  </div>
  <img class="mx-auto rounded-md xl:rounded-3xl max-w-full shadow-md" width="1300" src="{% static 'dashboard.png' %}" alt="" />
</div>
<!-- prettier-ignore -->
{% include 'offline/services.html' %} {% include 'offline/pricing.html' %} {% include 'offline/faq.html' %} {% include 'offline/contact.html' %} {%endblock %}

backend/templates/offline/login.html
{% extends 'offline/root.html' %} {% load static %} {% block content %}
<div style="min-height: calc(100vh - 104px)" class="grid place-content-center">
  <form id="registration" onsubmit="register_or_login(event, this)" class="main_form sm:w-400">
    <h1 class="text-headline text-2xl font-semibold">Login to your account</h1>
    <input type="hidden" value="{{csrf_token}}" name="csrfmiddlewaretoken" />
    <input type="text" placeholder="Username" name="username" />
    <input type="password" placeholder="Your password" name="password" />
    <a href="" class="hover:underline">I forgot my password :(</a>
    <button type="submit">Login</button>
  </form>
</div>
{%endblock %}

backend/templates/offline/navbar.html
{% load static %}
<header>
  <div id="navbar">
    <div>
      <a id="logo" href="/">
        <img src="{% static 'logo.svg' %}" alt="" width="25" />
        <span> StatusChecks </span>
      </a>
      {% if request.path == '/' %}
      <a href="#pricing" class="">Pricing </a>
      <a href="#services">Services</a>
      <a href="#faq">FAQ</a>
      {% endif %}
    </div>
    <div>
      {% if user.is_authenticated %}
      <a href="/home" class="main">Dashboard</a>
      {% else %}
      <a href="{% url 'website:login' %}">Sign in</a>
      <a href="{% url 'website:register' %}" class="main">Get started today</a>
      {% endif %}
    </div>
  </div>
  <div class="xl:hidden h-[76px]"></div>
  <div x-cloak x-data="{show_links_mobile:false}" class="xl:hidden top-0 left-0 fixed z-50 w-full bg-white">
    <div class="px-6 py-6 flex justify-between items-center">
      <a id="logo" href="/">
        <img src="{% static 'logo.svg' %}" alt="" width="25" />
        <span> StatusChecks </span>
      </a>
      <div @click="show_links_mobile=!show_links_mobile">
        <i :class="show_links_mobile ? 'fa-times' :'fa-bars'" class="fas fa-2xl text-secondary"></i>
      </div>
    </div>
    <div x-show="show_links_mobile" class="grid gap-10 px-8 py-6 shadow-lg">
      {% if user.is_authenticated %}
      <a href="/dashboard" class="main">Dashboard</a>
      {% else %}
      <a href="{% url 'website:login' %}" class="px-6">Login</a>
      <a href="{% url 'website:register' %}" class="main"> Register </a>
      {% endif %}
    </div>
  </div>
</header>

backend/templates/offline/pricing.html
<div id="pricing" class="px-6 lg:px-16 py-36 bg_gredient">
  <div x-data="{sub_annually: false}" class="max-w-1400 mx-auto">
    <h2 class="text-center text-5xl text-gray-800 pt-8 xl:pt-0 lg:mb-8 font-semibold font-lexend">Simple pricing for everyone</h2>
    <p class="mb-12 lg:w-9/12 mx-auto text-center text-lg">
      Whether you're a small business owner, an IT professional, or just someone who wants to ensure their online presence is always up and running, our monitoring service is the solution you've been
      looking for.
    </p>
    <div @click="sub_annually=!sub_annually" class="flex justify-center gap-4 mt-16 lg:mt-0 mx-auto mb-16" (click)="change_sub()">
      <span :class="!sub_annually? 'text-gray-700': 'text-gray-900 font-semibold'">Monthly</span>
      <div class="w-12 h-6 bg-gray-100 rounded-full relative xl:cursor-pointer">
        <div :class="!sub_annually? 'right-0': 'left-0'" class="h-full w-6 bg-secondary rounded-full absolute top-0"></div>
      </div>
      <span :class="sub_annually? 'text-gray-700': 'text-gray-900 font-semibold'">Annually</span>
    </div>
    <div
      x-data="{
        plans:[
        {
          name: 'free',
          price_monthly: 0,
          features: [
            { value: '5 monitors', included: true },
            { value: '5 minutes between checks', included: true },
            { value: '1 monitor page', included: true },
            { value: '1 alert email', included: true },
          ],
          show_subscribe: false,
        },
        {
          name: 'pro',
          price_monthly: 5,
          price_annually: 4,
          features: [
            { value: '50 monitors', included: true },
            { value: '1 minute between checks', included: true },
            { value: '5 monitor pages', included: true },
            { value: '3 alert emails', included: true },
          ],
          show_subscribe: true,
        },
        {
          name: 'business',
          price_monthly: 10,
          price_annually: 8,
          features: [
            { value: '100 monitors', included: true },
            { value: '30 seconds between checks', included: true },
            { value: '10 monitor pages', included: true },
            { value: '10 alert emails', included: true },
          ],
          show_subscribe: true,
        },
      ]
      }"
      *ngFor="plan in plans"
      class="pricing_container"
    >
      <template x-for="plan in plans">
        <div class="!text-black">
          <h2 class="bg-secondary uppercase text-gray-100" x-text="plan.name"></h2>
          <h3>
            <span x-show="plan.price_monthly == 0" style="font-size: 35px"> FREE </span>
            <span x-show="plan.price_monthly == 0" class="per_month">FOREVER</span>
            <span x-show="plan.price_monthly != 0" class="inline-flex mx-auto">
              <span x-show="sub_annually" x-text="plan.price_monthly"></span>
              <span x-show="!sub_annually" x-text="plan.price_annually"></span>
              <span class="text-3xl text-gray-400">$</span>
            </span>
            <span x-show="plan.price_monthly != 0" class="per_month">Per Month</span>
          </h3>
          <ul>
            <template x-for="feature of plan.features">
              <li class="flex gap-2 items-center justify-center">
                <i class="fas fa-check text-green-500" x-show="feature.included"></i>
                <i class="fas fa-times text-red-500" x-show="!feature.included"></i>
                <span x-text="feature.value"></span>
              </li>
            </template>
          </ul>
          <div class="w-full h-10" *ngIf="!plan.show_subscribe"></div>
          <div>
            <a href="{% if user.is_authenticated %}/plans{% else %}/register{% endif %}"> Get Started </a>
          </div>
        </div>
      </template>
    </div>
  </div>
</div>

backend/templates/offline/register.html
{% extends 'offline/root.html' %} {% load static %} {% block content %}
<div class="pb-24">
  <form id="registration" onsubmit="register_or_login(event, this, register=true)" class="main_form sm:w-550">
    <h1 class="text-headline text-2xl font-semibold">Create a FREE Account</h1>
    <input type="hidden" value="{{csrf_token}}" name="csrfmiddlewaretoken" />
    <input required type="text" placeholder="Username" name="username" />
    <input required type="email" placeholder="Email" name="email" />
    <input type="password" placeholder="Your password" name="password1" />
    <input type="password" placeholder="Confirm your password" name="password2" />
    <a href="{% url 'website:login' %}" class="w-content mx-auto hover:underline">I already have an account</a>
    <button type="submit" class="bg-secondary text-button rounded-md px-6 py-2 text-lg hover:bg-hover">Register</button>
  </form>
</div>
{%endblock %}

backend/templates/offline/root.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Statuscheks - FREE Monitoring Application For Your Websites.</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="icon" type="image/x-icon" href="{% static 'logo.svg' %}" />
    <link rel="stylesheet" href="{% static 'font.css' %}" />
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
    {% tailwind_css %}
    <style>
      [x-cloak] {
        display: none !important;
      }
    </style>
  </head>

  <body class="mx-auto font-inter">
    {% include 'offline/navbar.html' %} {% block content %}{% endblock %} {% if request.path == '/' %} {% include 'offline/footer.html' %} {% endif %}
    <div
      x-data="{show_message: false}"
      x-show="show_message"
      x-cloak
      x-transition.duration.500ms
      class="fixed z-20 w-content h-content max-w-300 bottom-10 left-0 right-0 mx-auto rounded-md bg-opacity-80 font-medium bg-gray-300 text-gray-600 px-6 py-3 capitalize leading-relaxed select-none"
      id="message_overlay"
    >
      <ul>
        <li>Logged in successfully</li>
      </ul>
      <span @click="show_message = false" class="hide"></span>
      <span @click="show_message = true" class="show"></span>
    </div>
    <script src="{% static 'script.js' %}" defer></script>
    <script src="{% static 'alpinejs.js' %}" defer></script>
    <script src="https://kit.fontawesome.com/d7fe9018d7.js" crossorigin="anonymous"></script>
  </body>
</html>

backend/templates/offline/services.html
{% load static %}
<div id="services" x-data="{slider_offset: 10}" class="max-w-1400 mx-auto pt-36 pb-52 grid gap-16 px-6 lg:px-16 2xl:px-0">
  <section class="text-center lg:w-9/12 mx-auto mb-16">
    <h2 class="text-4xl font-lexend mb-8">An easy way to monitor your services.</h2>
    <p class="text-gray-800 text-lg">Our service offers comprehensive monitoring for a wide range of systems and applications, including websites, API, servers, databases, and more.</p>
  </section>
  <section
    class="grid lg:flex justify-between gap-12"
    x-data="{
        features: [
            {
                offset: 10,
                active: true,
                name: 'Create monitor',
                title: 'Create a monitor for all your services.',
                text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla gravida sem elit, vitae suscipit leo dictum id. Cras sit amet lorem at metus lacinia pellentesque.'
            },
            {   
                offset: -75,
                active: false,
                name: 'Create page',
                title: 'Create a page and include one or all your monitors.',
                text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla gravida sem elit, vitae suscipit leo dictum id. Cras sit amet lorem at metus lacinia pellentesque.'
            },
            {
                offset: -158,
                active: false,
                name: 'Expose pages',
                title: 'Add the url of the page in your website to expose it to your customers.',
                text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla gravida sem elit, vitae suscipit leo dictum id. Cras sit amet lorem at metus lacinia pellentesque.'
            }
        ]
    }"
  >
    <template x-for="feature in features">
      <div
        :class="feature.active?'opacity-100':'opacity-80'"
        class="w-full grid gap-4 xl:cursor-pointer hover:opacity-100"
        @click="features.forEach(feature=>feature.active=false); feature.active=true; slider_offset=feature.offset"
      >
        <h3 :class="feature.active ? 'text-secondary font-semibold': 'text-gray-600'" class="text-lg" x-text="feature.name"></h3>
        <h4 :class="feature.active ? 'text-gray-900 ': 'text-gray-600'" class="text-lg font-medium" x-text="feature.title"></h4>
        <!-- <p :class="feature.active ? 'text-gray-700 ': 'text-gray-600'" x-text="feature.text"></p> -->
      </div>
    </template>
  </section>
  <section id="image_slider" class="relative h-[400px] lg:h-[900px] rounded-3xl overflow-auto lg:overflow-hidden">
    <div :style="{ left: `${slider_offset}%`}" class="absolute top-1/2 -translate-y-1/2 flex items-center gap-12 duration-500 ease-out">
      <div :class="slider_offset != 10 ? 'lg:opacity-25': 'opacity-100'" class="w-[350px] h-[250px] lg:w-[1000px] lg:h-[700px] duration-300">
        <img src="{% static 'picture_1.jpg' %}" class="rounded-3xl shadow-xl" alt="" />
      </div>
      <div :class="slider_offset != -75 ? 'lg:opacity-25': 'opacity-100'" class="w-[350px] h-[250px] lg:w-[1000px] lg:h-[700px] duration-300">
        <img src="{% static 'picture_2.jpg' %}" class="rounded-3xl shadow-xl" alt="" />
      </div>
      <div :class="slider_offset != -158 ? 'lg:opacity-25': 'opacity-100'" class="flex flex-col justify-center w-[350px] h-[250px] lg:w-[1000px] lg:h-[700px] duration-300">
        <img src="{% static 'picture_3.jpg' %}" class="rounded-3xl shadow-xl" alt="" />
      </div>
    </div>
  </section>
</div>